// Generated by 'unplugin-auto-import'
export {}
declare global {
  const $EmMsg: typeof import('element-plus')['ElMessage']
  const $EmMsgBox: typeof import('@/lib/msgBox')['EmMessageBox']
  const util: typeof import('@/utils')
}
